add namelist variable l_turb_standalone in EAM
- Default value is .false.
- l_turb_standalone = .true. is allowed only when single_column = .true.
- Placeholders are added to clubb_intr.F90 and shoc_intr.F90
  for upcoming code addition.

With this commit, if the user configures a SCM simulation and
sets l_turb_standalone = .true., the executable will run and write into atm.log
a line like

  shoc_init_e3sm: User has set l_turb_standalone = .t. and single_column = .t.

or

  clubb_ini_cam: User has set l_turb_standalone = .t. and single_column = .t.

After that, during the first time step, the job will abort and write into
atm.log a line like

  ERROR: shoc_tend_e3sm: standalone test not yet fully implemented.

or

  ERROR: clubb_tend_cam: standalone test not yet fully implemented.