Add namelist variable l_turb_standalone to EAM (#4)
* add namelist variable l_turb_standalone to EAM

- Default value is .false.
- l_turb_standalone = .true. is allowed only when single_column = .true.
- Placeholders are added to clubb_intr.F90 and shoc_intr.F90
  for upcoming code addition.

With this commit, if the user configures a SCM simulation and
sets l_turb_standalone = .true., the executable will run and write into atm.log
the following line:

  phys_ctl_readnl: User has set l_turb_standalone = .t. and single_column = .t.

After that, during the first time step, the job will abort and write into
atm.log a line like

  ERROR: shoc_tend_e3sm: standalone test not yet fully implemented.

or

  ERROR: clubb_tend_cam: standalone test not yet fully implemented.